# Generated by Django 3.1.2 on 2021-04-19 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
    ]
