# Generated by Django 3.1.2 on 2021-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='nickname',
            field=models.CharField(default='匿名', max_length=32, verbose_name='昵称'),
        ),
    ]
