# Generated by Django 3.1.2 on 2021-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够', to='storm.Keyword', verbose_name='文章关键词'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='storm.Tag', verbose_name='标签'),
        ),
    ]
