# Generated by Django 3.1.2 on 2021-04-20 20:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0002_auto_20210415_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
    ]
